name: race-compare
services:
- name: race-compare
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: wadewegner/race-compare
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-s
  source_dir: /