name: race-compare
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: wadewegner/race-compare
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: race-compare
  source_dir: /
  envs:
  - key: PUPPETEER_EXECUTABLE_PATH
    value: /usr/bin/chromium-browser
    scope: RUN_TIME
  - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
    value: "true"
    scope: RUN_TIME