ingress:
  rules:
  - component:
      name: race-compare
    match:
      path:
        prefix: /
name: race-compare
region: nyc
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: wadewegner/race-compare
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-s
  name: race-compare
  source_dir: /
  envs:
  - key: NODE_ENV
    scope: RUN_TIME
    value: production